SELECT
    T.TERRITORY_ID,
    ISNULL(
        R.TERR_NM,
        CONCAT(T.TERRITORY, ' (OPEN)')
    ) AS TERR_NM,
    T.REGION_ID,
    T.REGION AS REGION_NM,
    ROW_NUMBER() OVER (
        PARTITION BY T.TERRITORY_ID
        ORDER BY
            T.END_DT DESC
    ) AS RN
FROM
    tblTerritory T
    LEFT JOIN qryRoster R ON T.TERRITORY_ID = R.TERRITORY_ID
    AND R.ROLE = 'REP'
    AND R.[isLATEST?] = 1
    AND R.[STATUS] = 'ACTIVE'
WHERE
    T.TERRITORY_ID NOT LIKE '%OFF'
    AND T.TERRITORY_ID NOT LIKE 'MDR%'
    AND T.END_DT > GETDATE()